version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - APP_ENV=production
      - DEBUG=False
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./templates:/app/templates
    restart: unless-stopped 